### ISSUE TITLE
No tasks generated from my Overpass query

### ISSUE THREAD

**Issue by maciejs** [maproulette/maproulette-backend#331] opened 2017-08-16 22:00 UTC
I am trying to create Challenge for Hiking route without name in Poland. I created following query:

```
[timeout:180];
(
  relation["route"="hiking"]["name"!~".*"]["osmc:name"!~".*"](area:3600049715);
);
out body geom qt; 
```

http://overpass-turbo.eu/s/r1L it returns 238 relations. 

I put my query into MapRoulette Challenge id 2734 and now its status is Complete, but zero tasks were created.

**Comment by mvexel** [comment] 2017-08-16 22:58
Sorry, relations don't work (very well). One way to circumvent would be to save the resulting geometries from overpass Turbo as GeoJSON and use that. Let me know if that works. Again sorry!

**Comment by maciejs** [comment] 2017-08-17 17:51
Thanks! I had to remove some rubbish nodes from exported GeoJSON. After that, import worked fine.

**Comment by matkoniecz** [comment] 2017-08-17 20:02
seems to be duplicate of #259 but has a nice workaround

**Closed** 2024-07-24 02:29 UTC
